services:
    postgres:
        container_name: turnpoint-db
        ports:
            - "5431:5432"
        image: postgres
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./turnpoint_test_db:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
            interval: 5s
            timeout: 60s
            retries: 5
            start_period: 80s
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        command: bash -c "npx prisma migrate reset --force && npm run dev"
        environment:
            DATABASE_URL: "${DATABASE_URL}"
            PORT: "${SERVER_PORT}"
        depends_on:
            postgres:
                condition: service_healthy
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        command: bash -c "npm run preview"
        ports:
            - "8000:8000"
        depends_on:
            - server